#!/bin/bash
#
# AI Orchestrator - Quick Development Setup Script
# ================================================
# This script sets up the development environment with PLACEHOLDER API keys.
# 
# HOW TO USE:
# ===========
# 1. Run this script first:    ./quick-dev-setup.sh
# 2. Then inject real keys:    ./inject-dev-keys.sh  (you must create this file)
#
# ALTERNATIVE ONE-LINER (if you have inject-dev-keys.sh):
#    ./quick-dev-setup.sh && ./inject-dev-keys.sh
#
# The inject-dev-keys.sh file should contain your real API keys and will
# replace the placeholders in the config file. This file is git-ignored
# to keep your keys secure.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║       AI Orchestrator - Quick Development Setup           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Step 1: Create config directory
echo -e "${BLUE}[1/5]${NC} Creating configuration directory..."
CONFIG_DIR="$HOME/.config/ai-orchestrator"
mkdir -p "$CONFIG_DIR"
echo -e "${GREEN}✓${NC} Directory created: $CONFIG_DIR"

# Step 2: Create config.env with PLACEHOLDER API keys
echo -e "${BLUE}[2/5]${NC} Writing configuration with placeholder keys..."
CONFIG_FILE="$CONFIG_DIR/config.env"

cat > "$CONFIG_FILE" << 'EOF'
# AI Orchestrator Configuration
# Generated by quick-dev-setup.sh
# ================================
#
# ⚠️  IMPORTANT: These are PLACEHOLDER values!
# Run inject-dev-keys.sh to replace them with real API keys.
#

# ============================================
# API Keys (PLACEHOLDERS - Replace with real keys)
# ============================================

# OpenAI API Key
OPENAI_API_KEY=YOUR_OPENAI_KEY_HERE

# Anthropic API Key  
ANTHROPIC_API_KEY=YOUR_ANTHROPIC_KEY_HERE

# Google Gemini API Key
GEMINI_API_KEY=YOUR_GEMINI_KEY_HERE

# Moonshot (Kimi) API Key
MOONSHOT_API_KEY=YOUR_MOONSHOT_KEY_HERE

# ============================================
# Model Configurations
# ============================================

# OpenAI Model (architecture planning, roadmap generation)
OPENAI_MODEL=gpt-4o-mini

# Anthropic Model (coding, implementation, debugging)
ANTHROPIC_MODEL=claude-3-5-sonnet-20240620

# Google Gemini Model (reasoning, logic, test design)
GEMINI_MODEL=gemini-2.5-flash

# Moonshot Model (code review)
MOONSHOT_MODEL=moonshot-v1-8k

# ============================================
# Development Settings
# ============================================

# Enable all development tools
DEV_MODE=true
DEBUG_LOGGING=true
VERBOSE_OUTPUT=true

# Auto-fix settings
AUTO_FIX_ENABLED=true
MAX_FIX_ATTEMPTS=5
FIX_CONFIDENCE_THRESHOLD=0.7

# Execution settings
EXECUTION_TIMEOUT=300
MAX_RETRIES=3

# iOS Development (if available)
IOS_DEV_ENABLED=true
XCODE_INTEGRATION=true
EOF

echo -e "${GREEN}✓${NC} Configuration written to: $CONFIG_FILE"

# Step 3: Set proper permissions
echo -e "${BLUE}[3/5]${NC} Setting secure file permissions..."
chmod 600 "$CONFIG_FILE"
echo -e "${GREEN}✓${NC} Permissions set to 600 (owner read/write only)"

# Step 4: Install dependencies
echo -e "${BLUE}[4/5]${NC} Installing Python dependencies..."
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -f "$SCRIPT_DIR/requirements.txt" ]; then
    # Check if we're in a virtual environment
    if [ -z "$VIRTUAL_ENV" ]; then
        echo -e "${YELLOW}!${NC} No virtual environment detected. Creating one..."
        python3 -m venv "$SCRIPT_DIR/venv"
        source "$SCRIPT_DIR/venv/bin/activate"
        echo -e "${GREEN}✓${NC} Virtual environment created and activated"
    fi
    
    pip install --upgrade pip -q
    pip install -r "$SCRIPT_DIR/requirements.txt" -q
    echo -e "${GREEN}✓${NC} Python dependencies installed"
else
    echo -e "${YELLOW}!${NC} requirements.txt not found, skipping dependency installation"
fi

# Step 5: Enable development tools
echo -e "${BLUE}[5/5]${NC} Enabling development tools..."

# Create local .env symlink for convenience
if [ ! -f "$SCRIPT_DIR/.env" ]; then
    ln -sf "$CONFIG_FILE" "$SCRIPT_DIR/.env" 2>/dev/null || cp "$CONFIG_FILE" "$SCRIPT_DIR/.env"
    echo -e "${GREEN}✓${NC} Local .env file created"
fi

# Make scripts executable
if [ -d "$SCRIPT_DIR/scripts" ]; then
    chmod +x "$SCRIPT_DIR/scripts/"*.sh 2>/dev/null || true
    echo -e "${GREEN}✓${NC} Scripts made executable"
fi

if [ -d "$SCRIPT_DIR/mcp_server" ]; then
    chmod +x "$SCRIPT_DIR/mcp_server/"*.sh 2>/dev/null || true
    chmod +x "$SCRIPT_DIR/mcp_server/start.sh" 2>/dev/null || true
fi

# Success message
echo ""
echo -e "${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              Setup Complete! 🎉                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

echo -e "${CYAN}Configuration Summary:${NC}"
echo "  📁 Config Directory: $CONFIG_DIR"
echo "  📄 Config File: $CONFIG_FILE"
echo ""
echo -e "${CYAN}Enabled Models:${NC}"
echo "  🤖 OpenAI:    gpt-4o-mini (architecture, planning)"
echo "  🧠 Anthropic: claude-3-5-sonnet-20240620 (coding, debugging)"
echo "  💎 Gemini:    gemini-2.5-flash (reasoning, tests)"
echo "  🌙 Moonshot:  moonshot-v1-8k (code review)"
echo ""
echo -e "${RED}⚠️  IMPORTANT: API Keys Not Configured!${NC}"
echo ""
echo -e "${YELLOW}Next Step: Inject your real API keys${NC}"
echo "  Run: ${CYAN}./inject-dev-keys.sh${NC}"
echo ""
echo "  If you don't have inject-dev-keys.sh, create it with your keys:"
echo "  See README.dev.md for instructions."
echo ""
echo -e "${CYAN}Quick Start (after injecting keys):${NC}"
echo "  1. Activate venv:  source venv/bin/activate"
echo "  2. Run CLI:        ai-orchestrator --help"
echo "  3. Start server:   ./scripts/start-server.sh"
echo ""
