//
//  GenerateTestsCommand.swift
//  AI Orchestrator for Xcode
//
//  Command to generate unit tests using AI
//  Copyright © 2026 DebuggerLab. All rights reserved.
//

import Foundation
import XcodeKit

/// Command to generate unit tests for selected code
class GenerateTestsCommand: BaseCommand {
    
    override func perform(with invocation: XCSourceEditorCommandInvocation,
                         completionHandler: @escaping (Error?) -> Void) {
        
        guard let client = mcpClient else {
            completionHandler(createError(code: 1, message: "MCP client not initialized. Please check your settings."))
            return
        }
        
        let (code, _) = getSelectedCode(from: invocation)
        let language = getFileType(from: invocation)
        
        guard !code.isEmpty else {
            completionHandler(createError(code: 2, message: "No code to generate tests for."))
            return
        }
        
        // Determine test framework based on language
        let testFramework = getTestFramework(for: language)
        
        Logger.shared.log("Generating \(testFramework) tests...")
        showNotification(title: "AI Orchestrator", message: "Generating unit tests...")
        
        Task {
            do {
                let response = try await client.generateTests(
                    code: code,
                    language: language,
                    testFramework: testFramework
                )
                
                if response.success, let testCode = response.fixedCode ?? extractCodeBlock(from: response.content) {
                    // Parse the code to extract class/function names for test file naming
                    let parser = SwiftCodeParser()
                    let elements = parser.parse(code)
                    let testFileName = generateTestFileName(from: elements)
                    
                    // Format the test code
                    let formattedTests = formatTestCode(testCode, framework: testFramework)
                    
                    // Insert tests at the end of the current buffer
                    // In a real implementation, would create a new test file
                    let buffer = invocation.buffer
                    let insertLine = buffer.lines.count
                    
                    await MainActor.run {
                        self.insertCode(in: invocation, at: insertLine, code: "\n\n" + formattedTests)
                    }
                    
                    Logger.shared.log("Generated tests for \(testFileName)")
                    showNotification(title: "Tests Generated", message: "Unit tests added to buffer")
                    completionHandler(nil)
                } else {
                    completionHandler(self.createError(code: 3, message: "Failed to generate tests"))
                }
            } catch {
                Logger.shared.log("Error generating tests: \(error.localizedDescription)")
                completionHandler(self.createError(code: 4, message: error.localizedDescription))
            }
        }
    }
    
    /// Get appropriate test framework for language
    private func getTestFramework(for language: String) -> String {
        switch language {
        case "swift":
            return "XCTest"
        case "objc", "objcpp":
            return "XCTest"
        case "c", "cpp":
            return "GoogleTest"
        default:
            return "XCTest"
        }
    }
    
    /// Generate test file name from parsed elements
    private func generateTestFileName(from elements: [CodeElement]) -> String {
        // Find the first class or struct
        for element in elements {
            switch element.type {
            case .class, .struct:
                return "\(element.name)Tests.swift"
            default:
                continue
            }
        }
        return "GeneratedTests.swift"
    }
    
    /// Extract code block from markdown response
    private func extractCodeBlock(from content: String) -> String? {
        let pattern = "```(?:swift|objc|cpp)?\\n([\\s\\S]*?)```"
        guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else {
            return nil
        }
        
        let range = NSRange(content.startIndex..., in: content)
        guard let match = regex.firstMatch(in: content, options: [], range: range),
              let codeRange = Range(match.range(at: 1), in: content) else {
            return nil
        }
        
        return String(content[codeRange])
    }
    
    /// Format test code with proper structure
    private func formatTestCode(_ code: String, framework: String) -> String {
        var result = "// MARK: - Generated Unit Tests\n"
        result += "// Generated by AI Orchestrator for Xcode\n\n"
        
        if framework == "XCTest" && !code.contains("import XCTest") {
            result += "import XCTest\n\n"
        }
        
        result += code
        return result
    }
}
